mcom: have separate drafts and outbox folders

diff --git a/mcom b/mcom
--- a/mcom
+++ b/mcom
@@ -235,8 +235,12 @@ esac
 
 hdrs="$(printf '%s\n' "${hdrs#$NL}" | mhdr -)"
 
-outbox=$(mhdr -h outbox "$MBLAZE/profile" | sed "s:^~/:$HOME/:")
-if [ -z "$outbox" ]; then
+drafts=$(mhdr -h drafts "$MBLAZE/profile" | sed "s:^~/:$HOME/:")
+if [ -z "$drafts" ]; then
+	drafts=$(mhdr -h outbox "$MBLAZE/profile" |sed "s:^~/:$HOME/:") # Backwards compatibility
+fi
+outbox=$(mhdr -h outbox "$MBLAZE/profile" |sed "s:^~/:$HOME/:")
+if [ -z "$drafts" ]; then
 	if [ -z "$resume" ]; then
 		i=0
 		while [ -f "snd.$i" ]; do
@@ -249,13 +253,13 @@ if [ -z "$outbox" ]; then
 	draftmime="$draft.mime"
 else
 	if [ -z "$resume" ]; then
-		draft="$(true | mdeliver -v -c -XD "$outbox")"
+		draft="$(true | mdeliver -v -c -XD "$drafts")"
 		if [ -z "$draft" ]; then
-			printf '%s\n' "$0: failed to create draft in outbox $outbox." 1>&2
+			printf '%s\n' "$0: failed to create draft in mailbox $drafts." 1>&2
 			exit 1
 		fi
 	elif [ -z "$draft" ]; then
-		draft=$(mlist -D "$outbox" | msort -r -M | sed 1q)
+		draft=$(mlist -D "$drafts" | msort -r -M | sed 1q)
 	fi
 	draftmime="$(printf '%s\n' "$draft" | sed 's,\(.*\)/cur/,\1/tmp/mime-,')"
 fi
@@ -445,8 +449,7 @@ while :; do
 				stampdate "$draftmime"
 				if $sendmail <"$draftmime"; then
 					if [ "$outbox" ]; then
-						mv "$draftmime" "$draft"
-						mflag -d -S "$draft"
+						mrefile -v "$draft" "$outbox" |mflag -d -S >/dev/null
 					else
 						rm "$draft" "$draftmime"
 					fi
@@ -464,7 +467,7 @@ while :; do
 				stampdate "$draft"
 				if $sendmail <"$draft"; then
 					if [ "$outbox" ]; then
-						mflag -d -S "$draft"
+						mrefile -v "$draft" "$outbox" |mflag -d -S >/dev/null
 					else
 						rm "$draft"
 					fi
